// Config

var TIME_BETWEEN_CREATE = 2000;
var TIME_BETWEEN_DELETE = 2000;
var CALENDAR_NAME = "מערכת שעות";
var CALENDAR_COLOR = CalendarApp.Color.ORANGE;
var WEEKS_START_SHIFT = 1;
var WEEKS_END_SHIFT = 3;